package ru.third.inno.task.common.exception;

/**
 * Created by bot on 23.02.17.
 */
public class UserDaoException extends  Exception {
}
